name: polito

dependencies:
  - python=3.6
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - notebook
  - nb_conda_kernels
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - cartopy
  - seaborn
  - lightgbm
  - tensorflow=2.4
  - keras


  

