name: polito

dependencies:
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - notebook
  - nb_conda_kernels
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - cartopy
  - seaborn


  

